-- 1. Tabla de Productos (Inventario)
CREATE TABLE IF NOT EXISTS productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    precio NUMERIC NOT NULL,
    cantidad_en_stock INTEGER NOT NULL DEFAULT 0,
    categoria TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla de Promociones
CREATE TABLE IF NOT EXISTS promociones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    descuento_porcentaje NUMERIC NOT NULL,
    producto_id_aplicable BIGINT REFERENCES productos(id) ON DELETE SET NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    activa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Tabla de Ventas
CREATE TABLE IF NOT EXISTS ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_venta TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total NUMERIC NOT NULL,
    metodo_pago TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabla Detalles de Ventas (Relación muchos a muchos / 1 a muchos)
CREATE TABLE IF NOT EXISTS detalles_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES ventas(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES productos(id) ON DELETE SET NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC NOT NULL,
    subtotal NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabla de Reportes Guardados Automaticamente
CREATE TABLE IF NOT EXISTS reportes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_reporte TEXT NOT NULL, -- ej. 'Venta', 'Pedido de material'
    referencia_id BIGINT, -- ID de contexto (la venta id, etc)
    contenido JSONB NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Tabla de Empleados
CREATE TABLE IF NOT EXISTS empleados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    puesto TEXT NOT NULL,
    telefono TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Políticas RLS (Row Level Security) opcionales (Para permitir lecturas/escrituras públicas temporalmente)
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE promociones ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalles_venta ENABLE ROW LEVEL SECURITY;
ALTER TABLE reportes ENABLE ROW LEVEL SECURITY;
ALTER TABLE empleados ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir todo a anon en productos" ON productos FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en promociones" ON promociones FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en ventas" ON ventas FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en detalles_venta" ON detalles_venta FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en reportes" ON reportes FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en empleados" ON empleados FOR ALL USING (true);
