-- 1. Tabla de Productos (Inventario)
CREATE TABLE IF NOT EXISTS productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    precio NUMERIC NOT NULL,
    cantidad_en_stock INTEGER NOT NULL DEFAULT 0,
    categoria TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla de Promociones
CREATE TABLE IF NOT EXISTS promociones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    descuento_porcentaje NUMERIC NOT NULL,
    producto_id_aplicable BIGINT REFERENCES productos(id) ON DELETE SET NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    activa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2.5 Tabla de Empleados
CREATE TABLE IF NOT EXISTS empleados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    telefono TEXT,
    usuario TEXT UNIQUE,
    password TEXT,
    rol TEXT DEFAULT 'Cajero', -- 'Administrador' o 'Cajero'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Asegurarse de eliminar la columna puesto de instalaciones previas
ALTER TABLE empleados DROP COLUMN IF EXISTS puesto;

-- 3. Tabla de Ventas
CREATE TABLE IF NOT EXISTS ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_venta TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total NUMERIC NOT NULL,
    metodo_pago TEXT NOT NULL,
    empleado_id BIGINT REFERENCES empleados(id) ON DELETE SET NULL,
    efectivo_recibido NUMERIC,
    cambio_entregado NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabla Detalles de Ventas (Relación muchos a muchos / 1 a muchos)
CREATE TABLE IF NOT EXISTS detalles_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT REFERENCES ventas(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES productos(id) ON DELETE SET NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC NOT NULL,
    subtotal NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Tabla de Reportes Guardados Automaticamente
CREATE TABLE IF NOT EXISTS reportes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_reporte TEXT NOT NULL, -- ej. 'Venta', 'Pedido de material'
    referencia_id BIGINT, -- ID de contexto (la venta id, etc)
    contenido JSONB NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- 7. Vista de Ventas Diarias
CREATE OR REPLACE VIEW vista_ventas_diarias AS
SELECT 
    DATE(fecha_venta) as fecha,
    COUNT(id) as total_ventas,
    SUM(total) as ingresos_totales
FROM ventas
GROUP BY DATE(fecha_venta);

-- 8. Vista de Ventas Mensuales
CREATE OR REPLACE VIEW vista_ventas_mensuales AS
SELECT 
    DATE_TRUNC('month', fecha_venta) as mes,
    COUNT(id) as total_ventas,
    SUM(total) as ingresos_totales
FROM ventas
GROUP BY DATE_TRUNC('month', fecha_venta);

-- Políticas RLS (Row Level Security) opcionales (Para permitir lecturas/escrituras públicas temporalmente)
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE promociones ENABLE ROW LEVEL SECURITY;
ALTER TABLE ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalles_venta ENABLE ROW LEVEL SECURITY;
ALTER TABLE reportes ENABLE ROW LEVEL SECURITY;
ALTER TABLE empleados ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir todo a anon en productos" ON productos FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en promociones" ON promociones FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en ventas" ON ventas FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en detalles_venta" ON detalles_venta FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en reportes" ON reportes FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en empleados" ON empleados FOR ALL USING (true);

-- 9. Insertar usuario Administrador por defecto (Credenciales iniciales)
INSERT INTO empleados (nombre, telefono, usuario, password, rol)
VALUES ('Administrador General', '0000000000', 'admin', 'admin123', 'Administrador')
ON CONFLICT (usuario) DO NOTHING;

-- 10. Tabla de Recetas
CREATE TABLE IF NOT EXISTS recetas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    ingredientes TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. Tabla de Órdenes de Horneado
CREATE TABLE IF NOT EXISTS ordenes_horneado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pan TEXT NOT NULL,
    cantidad INTEGER NOT NULL,
    estado TEXT DEFAULT 'En Cola',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. Tabla de Mermas
CREATE TABLE IF NOT EXISTS mermas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pan TEXT NOT NULL,
    cantidad INTEGER NOT NULL,
    motivo TEXT,
    fecha_registro TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 13. Tabla de Pedidos
CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente TEXT NOT NULL,
    detalle TEXT NOT NULL,
    fecha TEXT,
    estado TEXT DEFAULT 'Pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 14. Tabla de Insumos
CREATE TABLE IF NOT EXISTS insumos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    cantidad TEXT NOT NULL,
    costo NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS e insertar políticas públicas para las nuevas tablas
ALTER TABLE recetas ENABLE ROW LEVEL SECURITY;
ALTER TABLE ordenes_horneado ENABLE ROW LEVEL SECURITY;
ALTER TABLE mermas ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE insumos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir todo a anon en recetas" ON recetas FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en ordenes_horneado" ON ordenes_horneado FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en mermas" ON mermas FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en pedidos" ON pedidos FOR ALL USING (true);
CREATE POLICY "Permitir todo a anon en insumos" ON insumos FOR ALL USING (true);
